#!/usr/bin/env ruby
irb     = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'
libs    = []
dirname = File.dirname(__FILE__)

libs << 'irb/completion'
libs << File.join(dirname, '..', 'lib', 'ambition')

exec "#{irb} -Ilib #{libs.map{|l| " -r #{l}" }.join} --simple-prompt"
